version: "3.1"

services:
  base:
    build:
      context: ./base
      dockerfile: Dockerfile
    image: mnetools/mne-python

  scheduler:
    depends_on:
      - base
    image: mnetools/mne-python
    hostname: mne-dask-scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]

  worker:
    depends_on:
      - base
    image: mnetools/mne-python
    hostname: mne-dask-worker
    command: ["dask-worker", "tcp://scheduler:8786"]

  worker_viz:
    depends_on:
        - base
    build:
      context: ./base
      dockerfile: Dockerfile.plot
    image: mnetools/mne-python-plot
    hostname: mne-dask-worker-plot
    command: ["dask-worker", "tcp://scheduler:8786"]
