name: Tests

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker compose build base
      - name: System info - base image
        run: docker run mnetools/mne-python python -c "import mne; mne.sys_info()"
      - name: Run base test
        run: docker run -v `pwd`:/opt/app/examples mnetools/mne-python python /opt/app/examples/tests/base.py
      - run: docker compose build jupyter
      - name: System info - jupyter image
        run: docker run mnetools/mne-python-jupyter ipython -c "import mne; mne.sys_info()"
      - name: Run jupyter test
        run: docker run -v `pwd`:/opt/app/examples mnetools/mne-python-jupyter ipython /opt/app/examples/tests/base.py
      - run: docker compose build plot
      - name: System info - plot image
        run: docker run mnetools/mne-python-plot python -c "import mne; mne.sys_info()"
      - name: Run plotting test
        run: docker run -v `pwd`:/opt/app/examples mnetools/mne-python-plot python /opt/app/examples/tests/plot.py
